# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 3306:8080
    container_name: my-jenkins-3
    volumes:
      - ~/jenkins_data:/var/jenkins_home